language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - build-tools-23.0.1
    - doc # Just the package-list is needed for JavaDoc task; OK to fetch the latest version here.

    - android-23
  licenses:
    - 'android-sdk-license-.*'

script:
  - TERM=dumb ./gradlew -PIS_PREDEXING_ENABLED=false assemble lint findbugs releaseJavadoc
