language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - doc # Just the package-list is needed for JavaDoc task

    - android-23
  licenses:
    - 'android-sdk-license-.*'

script:
  - TERM=dumb ./gradlew -PIS_PREDEXING_ENABLED=false assemble lint findbugs releaseJavadoc
